name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t alvianori/todo-list:latest .

    - name: Push Docker image to Docker Hub
      run: docker push alvianori/todo-list:latest
